### PR TITLE
cElementTree has been deprecated since Python 3.3 and removed in Python 3.9

### LINKED ISSUE #863: xml.etree.cElementTree was removed in Python 3.9
There are instances in the code base where cElementTree is used. This was deprecated and removed in Python 3.9.

Ref : https://github.com/python/cpython/pull/19108
Slightly related : https://github.com/minio/minio-py/issues/822

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #863

### CODE REVIEW

**Comment by harshavardhana** [comment]
@tirkarthi this is an incorrect fix

**Comment by tirkarthi** [comment]
I tried using compat since it had python 2/3 related imports. Can you be specific about the approach needed please?

**Comment by harshavardhana** [comment]
If celementTree is gone it should be completely remove and replaced with another XML alternative. The current fix is not doing anything other than just moving imports. 
@tirkarthi

**Comment by harshavardhana** [comment]
The correct fix is just replace all cElementTree with ElementTree @tirkarthi

**Comment by tirkarthi** [comment]
The project seems to support Python 2 and 3. Python 2 had ElementTree and cElementTree (accelerated version). Python 3 has accelerated version by default as ElementTree. Hence cElementTree was just an alias that was deprecated and removed. Always using ElementTree is a solution and more simple but it might cause slowdown in Python 2. If it's okay I can change it to that.

**Comment by harshavardhana** [comment]
> The project seems to support Python 2 and 3. Python 2 had ElementTree and cElementTree (accelerated version). Python 3 has accelerated version by default as ElementTree. Hence cElementTree was just an alias that was deprecated and removed. Always using ElementTree is a solution and more simple but it might cause slowdown in Python 2. If it's okay I can change it to that.

That is not a problem @tirkarthi

**Comment by tirkarthi** [comment]
Thanks @harshavardhana for the clarification. I have reverted the previous approach and made the suggested changes.

**Comment by tirkarthi** [comment]
I am not sure if the testcase failures are related to this PR.

**Pull request merged**
