### PR TITLE
return false if NoSuchBucket error occurs

### LINKED ISSUE #352: conn.bucket_exists() raises an error if the bucket does not exist
The expected result was for the function to return False.

Usage:

```
#!/usr/bin/env python

import os
import sys
from minio import Minio


conn = Minio(
    "{}:{}".format(
        os.getenv('MINIO_HOST'),
        os.getenv('MINIO_PORT')),
    access_key=os.getenv('AWS_ACCESS_KEY_ID'),
    secret_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
    insecure=True)
name = sys.argv[1]

if not conn.bucket_exists(name):
    conn.make_bucket(name)
```

Result:

```
Traceback (most recent call last):
  File "/bin/create_bucket", line 17, in <module>
    if not conn.bucket_exists(name):
  File "/usr/local/lib/python2.7/dist-packages/minio/api.py", line 288, in bucket_exists
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/minio/api.py", line 1546, in _url_open
    raise response_error.head(bucket_name, object_name)
minio.error.ResponseError: ResponseError: code: NoSuchBucket, message: Not Found, bucket_name: dbwal, object_name: None, request_id: B18FMJCFUCGD0T3E, host_id: , region:
```

### PR DESCRIPTION
**Pull request by bacongobbler**
Fixes #352

### CODE REVIEW

**Comment by bacongobbler** [comment]
I tried that, but I see the following error in the tests:

```.E.......................................................................
======================================================================
ERROR: test_bucket_exists_works (unit.bucket_exist_test.BucketExists)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bacongobbler/go/src/github.com/bacongobbler/minio-py/.eggs/mock-1.3.0-py2.7.egg/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/bacongobbler/go/src/github.com/bacongobbler/minio-py/tests/unit/bucket_exist_test.py", line 53, in test_bucket_exists_works
    false_result = client.bucket_exists('goodbye')
  File "/home/bacongobbler/go/src/github.com/bacongobbler/minio-py/minio/api.py", line 289, in bucket_exists
    headers=headers)
  File "/home/bacongobbler/go/src/github.com/bacongobbler/minio-py/minio/api.py", line 1552, in _url_open
    raise response_error.head(bucket_name, object_name)
  File "/home/bacongobbler/go/src/github.com/bacongobbler/minio-py/minio/error.py", line 142, in head
    self._set_error_response(bucket_name, object_name)
  File "/home/bacongobbler/go/src/github.com/bacongobbler/minio-py/minio/error.py", line 199, in _set_error_response
    if len(self._response.data) == 0:
TypeError: object of type 'NoneType' has no len()
----------------------------------------------------------------------
```

Is there another mock response I can try to get the tests passing?

**Comment by harshavardhana** [comment]
> Is there another mock response I can try to get the tests passing?

Checking locally.

**Comment by bacongobbler** [comment]
No worries. If you don't know the code off the top of your head I'll try to get to the bottom of this and see if we can get this merged. For now this hack works for us :)

**Comment by harshavardhana** [comment]
> No worries. If you don't know the code off the top of your head I'll try to get to the bottom of this and see if we can get this merged. For now this hack works for us :)

I know there are some good changes, going to make them locally and merge them with your change.

**Comment by harshavardhana** [comment]
> Thanks! <3

Just merged and thanks for your contribution! Please keep it coming.

**Pull request merged**
