### PR TITLE
api: Implement copyObject API.

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
Can you review this @balamurugana ?

**Comment by balamurugana** [comment]
minio/signer.py:239, we would need to fix query params here by sorting only by the key.

**Comment by harshavardhana** [comment]
> minio/signer.py:239, we would need to fix query params here by sorting only by the key.

This is fixed in a separate patch in listen bucket notifications.

**Comment by harshavardhana** [comment]
This patch is ready to go.

**Comment by balamurugana** [comment]
> This patch is ready to go.

Ok.  Merging the patch now.

**Pull request merged**
