### PR TITLE
Simplify python tests and reduce CPU usage.

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by vadmeste** [comment]
@harshavardhana, you probably need to remove reduce CPU usage in commit message

**Comment by harshavardhana** [comment]
No @vadmeste there is a reason why it's there .  Check locally with this change and without . Look at total time taken for completion of tests.

**Comment by deekoder** [comment]
Can this be merge?

**Comment by harshavardhana** [comment]
> Can this be merged?

Yes @deekoder

**Pull request merged**
