### PR TITLE
Fix Aliyun OSS multipart parsing

### PR DESCRIPTION
**Pull request by messense**
Aliyun OSS does not include xmlns in their multipart API responses.

References:

https://github.com/aliyun/aliyun-oss-python-sdk/blob/dbbb3176d4a0b76c10b8ae9551469f01075010fe/oss2/xml_utils.py#L158-L162

https://github.com/aliyun/aliyun-oss-python-sdk/blob/dbbb3176d4a0b76c10b8ae9551469f01075010fe/oss2/xml_utils.py#L51-L59

### CODE REVIEW

**Comment by nitisht** [comment]
@messense this SDK is meant to be AWS S3 API Compatible, so I don't think the changes are applicable here.

**Comment by messense** [comment]
@nitisht Aliyun OSS is supposed to be compatible with AWS S3, but apparently they messed up. The changes do not affect fully compatible S3 server implementation, so I think it should be fine.

https://www.alibabacloud.com/help/doc-detail/64919.htm

**Comment by nitisht** [comment]
I see, we'll take a look. Please take a look at CI failures..

**Comment by messense** [comment]
Ci failed with:

> Exception: HTTPSConnectionPool(host='play.min.io', port=9000): Max retries exceeded with url: /minio-py-test-1e40bb75-fd84-4308-97b5-773488bc2411/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faddd285750>: Failed to establish a new connection: [Errno 111] Connection refused',))\n", "duration": 6339, "message": "HTTPSConnectionPool(host='play.min.io', port=9000): Max retries exceeded with url: /minio-py-test-1e40bb75-fd84-4308-97b5-773488bc2411/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faddd285750>: Failed to establish a new connection: [Errno 111] Connection refused',))"}

I don't think it's related to this PR?

**Comment by harshavardhana** [comment]
We shouldn't silently be ignoring namespaces that would make our XML parsing exposed to bugs and would silently eat errors as well.  

@messense this PR is not acceptable since Aliyun decided to change the namespace for XML responses, this indicates that they want to diverge from S3 API in the future.  It is best to keep this PR as a fork in your project with the correct namespace added for Aliyun alone.

**Comment by nitisht** [comment]
You're right, Play demo server was down. It is running now, please push to the PR again to trigger the CI.

**Comment by messense** [comment]
> this PR is not acceptable since Aliyun decided to change the namespace for XML responses, this indicates that they want to diverge from S3 API in the future

Actually they didn't include namespace in `InitiateMultipartUploadResult` response, I think it's just a bug of Aliyun OSS rather than that they want to diverge from S3 API in the future.

**Comment by harshavardhana** [comment]
> Actually they didn't include namespace in `InitiateMultipartUploadResult` response, I think it's just a bug of Aliyun OSS rather than that they want to diverge from S3 API in the future.

They did that in 

- [ListObjects()](https://www.alibabacloud.com/help/doc-detail/31965.htm)
- [GetBucketLocation()](https://www.alibabacloud.com/help/doc-detail/31967.htm?spm=a2c63.p38356.b99.590.39a12234QjEGZ0) 
- [CopyObject()](https://www.alibabacloud.com/help/doc-detail/31979.htm?spm=a2c63.p38356.b99.602.38ef465ci8qbRe)

In almost all situations the namespace is different. We shouldn't patch minio-py to satisfy server changes - strict namespaces exist for a reason and we shouldn't silently make it work.

**Comment by harshavardhana** [comment]
This PR is out of scope for this library, it is better for Aliyun to fix their API responses - such that S3 SDKs work properly.

**Pull request closed without merging**
