### PR TITLE
Refactor XML handling of copy_object() API

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Review by BigUstad — APPROVED** [review]
LGTM.

**Review by ebozduman — CHANGES_REQUESTED** [review]
It looks like there is a clean-up issue left behind after PR #968, `Move http execution at one place`, is introduced.
There are still references to the removed class `ResponseError` as:

```
from minio.error import ResponseError
```

They are all in the following files:
   ../examples/*.py (22 files)
   *.md (4 files)
   tests*.py (8 files)

I noticed when I was running `copy_object.py` to test this PR.
Please clean them up.

**Comment by balamurugana** [comment]
> It looks like there is a clean-up issue left behind after PR #968, `Move http execution at one place`, is introduced.
> There are still references to the removed class `ResponseError` as:
> 
> ```
> from minio.error import ResponseError
> ```
> 
> They are all in the following files:
> ../examples/*.py (22 files)
> _.md (4 files) tests_.py (8 files)
> 
> I noticed when I was running `copy_object.py` to test this PR.
> Please clean them up.

Removed `from minio.error import ResponseError`

Other codes will be fixed separately in different PRs

**Review by ebozduman — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
