### PR TITLE
simplify functional tests

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Comment by kannappanr** [comment]
Please make sure that the functional tests run against different gateways and different server modes

**Comment by balamurugana** [comment]
> Please make sure that the functional tests run against different gateways and different server modes

I don't understand. Do you want me to run against different minio server/gateway modes and paste the results here? Also can you share how that will help here in finding issues in server than functional tests?

**Comment by harshavardhana** [comment]
> > Please make sure that the functional tests run against different gateways and different server modes
> 
> I don't understand. Do you want me to run against different minio server/gateway modes and paste the results here? Also can you share how that will help here in finding issues in server than functional tests?

Primarily because since its changing the tests fundamentally it's a precautionary step - because once released and goes into mint the cycle of fixing and making another release would be an extra effort that can be avoided right here. 

At the minimum, we should run these changes against S3 gateway - since server mode is already validated by GitHub actions.

**Comment by balamurugana** [comment]
Below is the result against minio gateway on minio server
```shell
[bala@localhost functional]$  SERVER_ENDPOINT=localhost:9000 ACCESS_KEY=minio SECRET_KEY=minio123 ENABLE_HTTPS=0 PYTHONPATH=$PYTHONPATH:/home/bala/git/src/github.com/minio/minio-py python tests.py
{"name": "minio-py:test_make_bucket_default_region", "status": "PASS", "args": {"bucket_name": "minio-py-test-9f13e32b-43e4-403f-80bf-34f03c379d02", "location": "default value ('us-east-1')"}, "function": "make_bucket(bucket_name, location)", "duration": 14}
{"name": "minio-py:test_list_buckets", "status": "PASS", "function": "remove_bucket(bucket_name)", "duration": 12}
{"name": "minio-py:test_put_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-46b51e15-a53d-478a-a8a1-da917e7d9583", "object_name": "9ef24a14-12fa-4ff1-b369-dcd6a63410cc-metadata", "length": 11534336, "data": "LimitedRandomReader(11 * MB)", "metadata": {"x-amz-meta-testing": "value", "test-key": "value2"}, "content_type": "application/octet-stream"}, "duration": 10849}
{"name": "minio-py:test_stat_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-7f4b4f01-3223-40ed-8b9c-9ef1c0b7c342", "object_name": "448a5ed2-383f-409d-85d4-d1bed78d7f45-metadata", "length": 11534336, "data": "LimitedRandomReader(11 * MB)", "metadata": {"X-Amz-Meta-Testing": "value"}, "content_type": "application/octet-stream"}, "duration": 10803}
{"name": "minio-py:test_get_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-31e3d64a-736e-4798-9298-a9cd49f364b4", "object_name": "7f4500d1-0701-4a88-8dd4-0debf3d6cb49"}, "duration": 995}
{"name": "minio-py:test_list_objects", "status": "PASS", "args": {"bucket_name": "minio-py-test-2e379f72-3aa1-43ad-9e00-fb875baecc41", "object_name": "378bbcc3-d314-4142-8164-80302a4260aa", "recursive": true}, "duration": 48}
{"name": "minio-py:test_remove_incomplete_upload", "status": "PASS", "args": {"bucket_name": "minio-py-test-7161b141-eba1-4e7a-b3d4-3c565161854e", "object_name": "70806840-23e5-4c2b-9f88-c456408b99b9"}, "duration": 86}
{"name": "minio-py:test_presigned_get_object_default_expiry", "status": "PASS", "args": {"bucket_name": "minio-py-test-b84a1599-7880-4129-8b30-f97fe82d20ab", "object_name": "b8435e71-51ea-4fc4-8d56-a9547a16555b"}, "duration": 22}
{"name": "minio-py:test_presigned_put_object_default_expiry", "status": "PASS", "args": {"bucket_name": "minio-py-test-d6f7ce16-ee32-40e5-b753-c7221ce94557", "object_name": "9c985df5-9dfe-4248-8be9-de543bca04cb"}, "duration": 17}
{"name": "minio-py:test_presigned_post_policy", "status": "PASS", "args": {"bucket_name": "minio-py-test-960b7a3d-a637-4115-97ef-a0f0f467dfc9", "post_policy": {"prefix": "objectPrefix/", "expires_in_days": 10}}, "duration": 5}
{"name": "minio-py:test_copy_object_no_copy_condition", "status": "PASS", "args": {"bucket_name": "minio-py-test-f7bd041d-2101-47d3-9a1b-c396d80ccbdf", "object_source": "9c6744bb-3c02-4b63-8350-44a5e00bc9cf-source", "object_name": "9c6744bb-3c02-4b63-8350-44a5e00bc9cf-copy"}, "duration": 33}
{"name": "minio-py:test_select_object_content", "status": "PASS", "args": {"bucket_name": "minio-py-test-04264cf8-9f66-472b-ab83-b70a1b3e7fab", "object_name": "test.csv"}, "duration": 43}
{"name": "minio-py:test_get_bucket_policy", "status": "PASS", "args": {"bucket_name": "minio-py-test-728a9d94-c25b-4808-819c-3bdc12a877ab"}, "duration": 10}
{"name": "minio-py:test_set_bucket_policy_readonly", "status": "PASS", "args": {"bucket_name": "minio-py-test-8a93c046-7bcb-45fc-b171-b42c7b871854"}, "duration": 50}
{"name": "minio-py:test_get_bucket_notification", "status": "NA", "args": {"bucket_name": "minio-py-test-4692e0be-3849-4987-b67e-a52b3267167c"}, "alert": "Not Implemented", "duration": 11}
{"name": "minio-py:test_remove_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-22b398f6-5b8e-4007-8892-27fbfe98319f", "object_name": "efde9fd3-c573-4066-abf7-206b1654c922"}, "duration": 45}
{"name": "minio-py:test_remove_objects", "status": "PASS", "args": {"bucket_name": "minio-py-test-e543520a-eb4e-447b-a08a-84c862e24723", "objects_iter": ["prefix-0", "prefix-1", "prefix-2", "prefix-3", "prefix-4", "prefix-5", "prefix-6", "prefix-7", "prefix-8", "prefix-9"]}, "duration": 297}
{"name": "minio-py:test_remove_bucket", "status": "PASS", "args": {"bucket_name": "minio-py-test-0111c792-cef7-4f28-bcc0-9651c0c84651"}, "duration": 13}
[bala@localhost functional]$ SERVER_ENDPOINT=localhost:9000 ACCESS_KEY=minio SECRET_KEY=minio123 ENABLE_HTTPS=0 MINT_MODE=full PYTHONPATH=$PYTHONPATH:/home/bala/git/src/github.com/minio/minio-py python tests.py
{"name": "minio-py:test_make_bucket_default_region", "status": "PASS", "args": {"bucket_name": "minio-py-test-5940409f-7137-4d3d-943e-2a610acc115f", "location": "default value ('us-east-1')"}, "function": "make_bucket(bucket_name, location)", "duration": 11}
{"name": "minio-py:test_make_bucket_with_region", "status": "PASS"}
{"name": "minio-py:test_negative_make_bucket_invalid_name", "status": "PASS", "args": {"location": "default value ('us-east-1')", "bucket_name": ["minio-py-test-2ab2738b-efbe-4b2b-b63b-21a0da2c42bb.", ".minio-py-test-2ab2738b-efbe-4b2b-b63b-21a0da2c42bb", "minio-py-test-2ab2738b-efbe-4b2b-b63b-21a0da2c42bb...abcd"]}, "function": "make_bucket(bucket_name, location)", "duration": 24}
{"name": "minio-py:test_list_buckets", "status": "PASS", "function": "remove_bucket(bucket_name)", "duration": 10}
{"name": "minio-py:test_fput_object_small_file", "status": "PASS", "args": {"bucket_name": "minio-py-test-33ace5b4-4c6f-436c-a4bf-e375a83ae6cb", "object_name": "a2806376-0b91-4cb0-9420-3035eeaea62a-f", "file_path": "datafile-1-MB", "metadata": {"x-amz-storage-class": "STANDARD_IA"}}, "duration": 60}
{"name": "minio-py:test_fput_object_large_file", "status": "PASS", "args": {"bucket_name": "minio-py-test-b121bcc7-2099-4052-aa7d-043951f26b0c", "object_name": "bf24694d-8c6c-4e36-b612-854610726aec-large", "file_path": "datafile-11-MB", "metadata": {"x-amz-storage-class": "STANDARD_IA"}}, "duration": 392}
{"name": "minio-py:test_fput_object_with_content_type", "status": "PASS", "args": {"bucket_name": "minio-py-test-5e50bf5b-ec42-413e-8745-c3116162093c", "object_name": "a90ca76d-6e07-4613-918f-018f8fdee7d8-f", "file_path": "datafile-1-MB", "metadata": {"x-amz-storage-class": "STANDARD_IA"}, "content_type": "application/octet-stream"}, "duration": 119}
{"name": "minio-py:test_copy_object_no_copy_condition", "status": "PASS", "args": {"bucket_name": "minio-py-test-92f3c142-9cf0-4834-9c98-82c396b978f2", "object_source": "36bd248d-7a22-4189-9c20-b330afe11c5a-source", "object_name": "36bd248d-7a22-4189-9c20-b330afe11c5a-copy"}, "duration": 88}
{"name": "minio-py:test_copy_object_etag_match", "status": "PASS", "args": {"bucket_name": "minio-py-test-9722361b-d38b-40d3-b17e-91e27e3e1325", "object_source": "c52ca20d-9e7f-43c6-a4e0-b877d70f7797-source", "object_name": "c52ca20d-9e7f-43c6-a4e0-b877d70f7797-copy", "conditions": {"set_match_etag": "81112c14a2670ca3a597710d78a55ed5"}}, "duration": 119}
{"name": "minio-py:test_copy_object_with_metadata", "status": "PASS", "args": {"bucket_name": "minio-py-test-02ef5623-945e-4401-80d9-d339a783da7d", "object_source": "917dfd05-4231-482d-a5eb-bd3f47d922ce-source", "object_name": "917dfd05-4231-482d-a5eb-bd3f47d922ce-copy", "metadata": {"testing-string": "string", "testing-int": 1}}, "duration": 86}
{"name": "minio-py:test_copy_object_negative_etag_match", "status": "PASS", "args": {"bucket_name": "minio-py-test-3077ca75-dab9-455d-8297-cdd9e320a281", "object_source": "cf68fc34-3a96-4fb6-b342-1f3a28afb7bb-source", "object_name": "cf68fc34-3a96-4fb6-b342-1f3a28afb7bb-copy", "conditions": {"set_match_etag": "test-etag"}}, "duration": 74}
{"name": "minio-py:test_copy_object_modified_since", "status": "PASS", "args": {"bucket_name": "minio-py-test-6c4454ed-4222-4cc8-9d86-10d678c996a7", "object_source": "69e87da0-b98e-40ca-8fc0-070ba440fbf1-source", "object_name": "69e87da0-b98e-40ca-8fc0-070ba440fbf1-copy", "conditions": {"set_modified_since": "Tue Apr  1 00:00:00 2014"}}, "duration": 85}
{"name": "minio-py:test_copy_object_unmodified_since", "status": "PASS", "args": {"bucket_name": "minio-py-test-4c2f1121-5fd9-485a-9a47-9b10f55bb6a1", "object_source": "630b09bd-4ef8-41d3-a065-da9a923befa5-source", "object_name": "630b09bd-4ef8-41d3-a065-da9a923befa5-copy", "conditions": {"set_unmodified_since": "Tue Apr  1 00:00:00 2014"}}, "duration": 65}
{"name": "minio-py:test_put_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-66af7cb3-8d2f-4b81-b1c6-a0a1e34ce27b", "object_name": "0ef663a2-494a-4e5c-920e-bb9c139e0db0-metadata", "length": 11534336, "data": "LimitedRandomReader(11 * MB)", "metadata": {"x-amz-meta-testing": "value", "test-key": "value2"}, "content_type": "application/octet-stream"}, "duration": 11015}
{"name": "minio-py:test_negative_put_object_with_path_segment", "status": "PASS", "args": {"bucket_name": "minio-py-test-e7f64de1-d31d-461b-9763-f38308644fca", "object_name": "/a/b/c/e3b19d0e-377b-4629-b311-cb075ddd6698"}, "duration": 11}
{"name": "minio-py:test_stat_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-e677de24-a250-4d1a-a1ce-f493033973a9", "object_name": "6407bedc-00c3-4e0f-9b97-cc4b36c4c8a3-metadata", "length": 11534336, "data": "LimitedRandomReader(11 * MB)", "metadata": {"X-Amz-Meta-Testing": "value"}, "content_type": "application/octet-stream"}, "duration": 11190}
{"name": "minio-py:test_get_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-f37d14b1-ccc1-4ddb-9bdd-c8ef68a1cca5", "object_name": "0c41285f-ab3d-46cc-b175-f9ee398b0f33"}, "duration": 992}
{"name": "minio-py:test_fget_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-8d121d6a-4752-4d67-9590-f9b086020cb4", "object_name": "45e14292-d935-4466-8c06-0d99e85086b5", "file_path": "/tmp/tmpxncpa6rh"}, "duration": 1309}
{"name": "minio-py:test_get_partial_object_with_default_length", "status": "PASS", "args": {"bucket_name": "minio-py-test-2b0f63d0-e0dc-44e2-a59f-f240d445ba90", "object_name": "9ad1ef2d-95d5-4f65-b63f-cab86cea336a", "offset": 1047576}, "duration": 1060}
{"name": "minio-py:test_get_partial_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-8127c74a-60d2-49f7-9467-ce05936b5bd4", "object_name": "ae957b42-0f28-48c9-8fb0-911a9ad8f5b6", "offset": 524288}, "duration": 1155}
{"name": "minio-py:test_list_objects", "status": "PASS", "args": {"bucket_name": "minio-py-test-7313a30f-6ed4-48d5-96b9-3439a91beec2", "object_name": "e13158a6-1275-432e-b74b-befce0adf56f", "recursive": true}, "duration": 72}
{"name": "minio-py:test_list_objects_with_prefix", "status": "PASS", "args": {"bucket_name": "minio-py-test-addb4ef4-79ef-4b8a-ad61-a7343d4653ec", "object_name": "ceed27ae-3ccd-4139-b499-35856734a55d", "prefix": "Several prefix/recursive combinations are tested", "recursive": "Several prefix/recursive combinations are tested"}, "duration": 113}
{"name": "minio-py:test_list_objects_with_1001_files", "status": "PASS", "args": {"bucket_name": "minio-py-test-b02c1c37-a1f0-431c-9c67-fad2718fc299", "object_name": "ba0a534e-ddb0-464a-bbd2-f874d85bd729_0 ~ ba0a534e-ddb0-464a-bbd2-f874d85bd729_1000"}, "duration": 46421}
{"name": "minio-py:test_remove_incomplete_upload", "status": "PASS", "args": {"bucket_name": "minio-py-test-25247b59-04c1-4300-9010-6b48a6581a4a", "object_name": "133e3e8d-34d2-4bbf-b94a-05fe30790140"}, "duration": 92}
{"name": "minio-py:test_list_objects_v2", "status": "PASS", "args": {"bucket_name": "minio-py-test-32da411f-2854-4bc8-ade5-d2e83cf465a8", "object_name": "f0dd1d6a-f20d-4d15-a83e-c0dacaaf8463", "recursive": true}, "duration": 39}
{"name": "minio-py:test_presigned_get_object_default_expiry", "status": "PASS", "args": {"bucket_name": "minio-py-test-491d7aeb-03c9-46d7-b99f-6c9fc6a60b92", "object_name": "6e67c46f-aade-4aad-b2f4-31b4a61c97b2"}, "duration": 22}
{"name": "minio-py:test_presigned_get_object_expiry", "status": "PASS", "args": {"bucket_name": "minio-py-test-3a8e01bc-0abe-4d6d-953f-e7a36a4e782c", "object_name": "2a6ad104-54f5-467d-ad3d-b55b67d6c225", "presigned_get_object_url": "http://localhost:9000/minio-py-test-3a8e01bc-0abe-4d6d-953f-e7a36a4e782c/2a6ad104-54f5-467d-ad3d-b55b67d6c225?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200424%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200424T073754Z&X-Amz-Expires=120&X-Amz-SignedHeaders=host&X-Amz-Signature=5251bae19046399b2b51d8635319370bc02f09408011af81051f72589bf3dc2d", "response.status": 200, "response.reason": "OK", "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"1024\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/octet-stream\"], \"etag\": [\"ETag\", \"\\\"5592dae1942ef530c2ef195afbf6d67c\\\"\"], \"last-modified\": [\"Last-Modified\", \"Fri, 24 Apr 2020 07:37:54 GMT\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.GOGET\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"1608B15B43E1A5E6\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 24 Apr 2020 07:37:54 GMT\"]}}", "response._body": "blnmnghhvoojwltravfumzjhmnyqsggtbjixmyscqaxsmwjceoollzvlobmhdsdfouzosztabmahkowkxrbvmvqnoaarobeyvdgxnwbrhtuvqrtbpuznboqulluhahesknobyavkzpfdvcgqtttuqpmtalviyhhqyesyfgyghihilmfcstpypqhytrrnofohcjtoxiqbiqyilyifwjpeocppxdiczyufpkjieeiquugkfkxajpfhwddnobpvolvztpvtsrazkmqvvzggqocrmkewmidfwjipdiocdpypavenjkenqusesywtssuvtwkpofifealxxbhdnwizcvxofspczqqtlrrtpdagaefvbjvnjdemcbhzmpwgcxtmbticfbwjhltkrzxamftflxryrstfspayxedvmiaijjwexybgnzkdbvcmdsgztzyblbfhplgruptxrjrauplteikkwgtiezevgamqjluhcjrqvokrvevggoxyunhksqdqxsmhrxqnftdgypxcomyzrtvzryedaocxpufsyqullnwdfsghrzbjjhhwsrfhlhnvknacxuertliubhbdfiroxdcgksovmwobyjwbduunwkhjuuwcfrsenhqfvsgxcvikqjherqecmrqprxasaqujkdawfxncpcbwfptwkkiiudgfbahhydwoenfmjktwunxiofbzsvqgzwgmyswgsuklzykomwssmoiozyxcqjtfyzaowlasvmbkqmzewjbaxzdwdihwavpwlejknlsalfjcfyizgrilrlmcwxdbyjagvtrgigkcclabcngocuemnjucemdxccshmbtnzwyfpclwkyggveildxuzgqjugzwnypddikrycujzuicemxuvlldpzjxizkhenpfybfjahjqncsgwddcztumqfyrqnxrbalqgupbzdeederoktqnjnraszmjhefpogpnlhhixmyjuisexekksxgkpodzvqqaudxnmksnaijvreniatltbppbnbalk", "response.status-2": 403, "response.reason-2": "Forbidden", "response.headers-2": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.GOGET\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"1608B15BBB7787EB\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 24 Apr 2020 07:37:56 GMT\"]}}", "response._body-2": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>2a6ad104-54f5-467d-ad3d-b55b67d6c225</Key><BucketName>minio-py-test-3a8e01bc-0abe-4d6d-953f-e7a36a4e782c</BucketName><Resource>/minio-py-test-3a8e01bc-0abe-4d6d-953f-e7a36a4e782c/2a6ad104-54f5-467d-ad3d-b55b67d6c225</Resource><RequestId>1608B15BBB7787EB</RequestId><HostId>fa2e040d-1cbc-4ab8-a166-d381b5dde763</HostId></Error>"}, "duration": 2034}
{"name": "minio-py:test_presigned_get_object_response_headers", "status": "PASS", "args": {"bucket_name": "minio-py-test-2ca600f0-7268-4d61-a781-f855e41e4f00", "object_name": "ab948d5b-b9e2-40ee-8d1c-63920160b252", "content_type": "text/plain", "content_language": "en_US", "presigned_get_object_url": "http://localhost:9000/minio-py-test-2ca600f0-7268-4d61-a781-f855e41e4f00/ab948d5b-b9e2-40ee-8d1c-63920160b252?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200424%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200424T073756Z&X-Amz-Expires=120&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=80acc38f4d03cbade45b838b11d198816eec6664e82394a8825d07743255db53", "response.status": 200, "response.reason": "OK", "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-language\": [\"Content-Language\", \"en_US\"], \"content-length\": [\"Content-Length\", \"1024\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"text/plain\"], \"etag\": [\"ETag\", \"\\\"605f3d30a4af2f9736abd4e1caecd124\\\"\"], \"last-modified\": [\"Last-Modified\", \"Fri, 24 Apr 2020 07:37:56 GMT\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.GOGET\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"1608B15BBD7A6574\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 24 Apr 2020 07:37:56 GMT\"]}}", "response._body": "cxlwqyqorkzmsthjkqspqnarejgjmawejpzleqiegmktwlmrdvlqbogqmfzofwipmhhcocngoqdqpbogfulonkkmbznpzxlnndondxqajywsqwhfbxomiwzjnuccmzngaammvalezzjzaqdhtktwbqphcmlcidauwvwnjpsfwzsuvlcfavrfxmhrockxwoyuigduvxlzslfxuskkyuqsofcknybiquabsawinmwbqkauovistitulorfdnbhzqyeiwzsqicvcthuwivmaeptaavgwuhvnsftvmxiighgyukqrscrvvhabiufvrodbczkoucetfgzjgnexpnsruqrrjzepmpcqhthdjzlotowlzgmcdrcrhzgwnjuldzpdpmrmxqotucfjqyrqizmsktlrabdlfaenlgbyysxpllbuieddejncxrypoxytyppvvklfltwymkgqkvcymlhszsvvadjmtegswbvgrxxctiyimzpfjcocracbcykuokpdnytkrsdqqngqmzojafrdmxbdcbagxfpzaytozvhsrikyfwxukacbowtujlnvnbfyukrhhuubswlrxevydllqpkxdruddmisrpwaoprxjivxhfmlmqjkigojiprwslabgcdpvitfbqeeeijbmwgbhpxeomjpyokggojrscfolcfxkohgndkhsnysyhlhyewnrzaxaevvthusxhjozgwlhnwckokfiqpoibnkkrwjvrlmwafgsesjvsdyzbiuqidmrepsultpagajbkmixnbfxfvnhfrvbnejudzgbhztfioagaftuebozctgjishxpxjeapmjjxnqdeelyvywziakvtroskenqvjtckqdsxbiwwfblyetejacmspgtthhzsxnyjhwgfydvvrpsecjtkdujurnhhewilhlgeugtexjenmbzyddzhupfdtxagaubrkgmnplztpysgyydfvpfbiaowbteqzqvhfycudfhyenniyxbbecfaiegxtjdtcuckwqxip", "returned_content_type": "text/plain", "returned_content_language": "en_US"}, "duration": 38}
{"name": "minio-py:test_presigned_put_object_default_expiry", "status": "PASS", "args": {"bucket_name": "minio-py-test-1a14dc04-b141-4569-8817-cc2d7068627d", "object_name": "237bf1c3-5419-4ba2-9deb-bda29b459651"}, "duration": 22}
{"name": "minio-py:test_presigned_put_object_expiry", "status": "PASS", "args": {"bucket_name": "minio-py-test-57060c1c-5c90-4b0b-978f-d889c6305df7", "object_name": "dec718e8-9847-46d0-a2c8-0a2c6a4bc62e"}, "duration": 2036}
{"name": "minio-py:test_presigned_post_policy", "status": "PASS", "args": {"bucket_name": "minio-py-test-dcef9db8-a52f-4172-b287-78fb37d5a1d0", "post_policy": {"prefix": "objectPrefix/", "expires_in_days": 10}}, "duration": 19}
{"name": "minio-py:test_thread_safe", "status": "PASS", "args": {"bucket_name": "minio-py-test-ad94f22e-54fc-4458-a38b-800b5a5af979", "object_name": "73662e9f-2868-4e76-aeb8-de2f4239be38"}, "duration": 2215}
{"name": "minio-py:test_get_bucket_policy", "status": "PASS", "args": {"bucket_name": "minio-py-test-1bff7c7a-b334-4837-aab3-867cb20b569d"}, "duration": 11}
{"name": "minio-py:test_set_bucket_policy_readonly", "status": "PASS", "args": {"bucket_name": "minio-py-test-e3d69a31-6e65-4bab-b2a8-e13698effe56"}, "duration": 17}
{"name": "minio-py:test_set_bucket_policy_readwrite", "status": "PASS", "args": {"bucket_name": "minio-py-test-ebe3edf3-694e-49b8-9acd-5982a33736a0"}, "duration": 18}
{"name": "minio-py:test_get_bucket_notification", "status": "NA", "args": {"bucket_name": "minio-py-test-8a76f3cf-c51d-4ec5-943c-f96a736d12d2"}, "alert": "Not Implemented", "duration": 8}
{"name": "minio-py:test_select_object_content", "status": "PASS", "args": {"bucket_name": "minio-py-test-4c6e7780-b6d0-4a95-bf55-8279a5c0f3d1", "object_name": "test.csv"}, "duration": 25}
{"name": "minio-py:test_remove_object", "status": "PASS", "args": {"bucket_name": "minio-py-test-cc909d5a-b81c-45de-b2cd-d2d6d49d434f", "object_name": "a645d508-71c6-431b-bf25-9ba384bd711b"}, "duration": 43}
{"name": "minio-py:test_remove_objects", "status": "PASS", "args": {"bucket_name": "minio-py-test-d806ac89-ed2c-4886-aeb2-1036f34102cd", "objects_iter": ["prefix-0", "prefix-1", "prefix-2", "prefix-3", "prefix-4", "prefix-5", "prefix-6", "prefix-7", "prefix-8", "prefix-9"]}, "duration": 311}
{"name": "minio-py:test_remove_bucket", "status": "PASS", "args": {"bucket_name": "minio-py-test-687deece-de3e-43a4-933d-10fd8ed9d010"}, "duration": 22}
[bala@localhost functional]$
```

**Pull request merged**
