### PR TITLE
Add support for ISO time with and without fractional seconds.

### PR DESCRIPTION
**Pull request by mikijov**
Some non Amazon S3 implementations are not consistent about including fractional seconds in the timestamp. The change allows parsing of both `2019-07-10T14:23:39.231Z` and `2019-07-10T14:23:39Z`.

### CODE REVIEW

**Comment by harshavardhana** [comment]
Can you state which Amazon S3 implementation is this ? Please mention them in the comment. We may way to remove this code in future, as this should be seen as a workaround.

**Comment by mikijov** [comment]
Added comment into the code. I encountered this issue on Dell EMC ECS.

**Comment by mikijov** [comment]
Build job failed due to some timeout, I have to close/re-open the PR to trigger the build.

**Comment by mikijov** [comment]
Hi @ebozduman, @vadmeste, are there any concerns merging this? We actually need this in production, and we are struggling patching minio-py on the fly...

**Comment by mikijov** [comment]
Thanks for approval. Will someone be able to merge it?

**Pull request merged**
