### PR TITLE
Add support for user server

### PR DESCRIPTION
**Pull request by taran-p**
Added main() function to some examples

Allow testing some examples on given server using environment variables

### CODE REVIEW

**Review by balamurugana — CHANGES_REQUESTED** [review]
If you want to test your server, use [functional tests](https://github.com/minio/minio-py/tree/master/tests/functional) than complicating examples.

**Comment by donatello** [comment]
> If you want to test your server, use [functional tests](https://github.com/minio/minio-py/tree/master/tests/functional) than complicating examples.

@balamurugana I'm helping Taran - we're just trying to get to a situation where examples can run in CI so that they are automatically up to date with library code.

**Comment by harshavardhana** [comment]
> > If you want to test your server, use [functional tests](https://github.com/minio/minio-py/tree/master/tests/functional) than complicating examples.
> 
> @balamurugana I'm helping Taran - we're just trying to get to a situation where examples can run in CI so that they are automatically up to date with library code.

If we want to do that perhaps then `examples` must have some provision to load a separate `config.py` file instead of each file being modified in the manner it's being done right now.

It kind of fails to be an example at his point if it's modified in this manner. 

My suggestion is something like this 

```
if ci: 
  from config import *
   ... use the imported values
```

**Comment by donatello** [comment]
> If we want to do that perhaps then `examples` must have some provision to load a separate `config.py` file instead of each file being modified in the manner it's being done right now.
> 
> It kind of fails to be an example at his point if it's modified in this manner.
> 
> My suggestion is something like this
> 
> ```
> if ci: 
>   from config import *
>    ... use the imported values
> ```

Yeah, we're going to something like this to reduce the code in the examples - this initial change is just for some discussion and feedback. No need to merge right away.

In addition to CI, it would be good if the examples can be run locally with a user specified server rather than play - so the idea is to get this info from env vars.

**Comment by balamurugana** [comment]
> > If you want to test your server, use [functional tests](https://github.com/minio/minio-py/tree/master/tests/functional) than complicating examples.
> 
> @balamurugana I'm helping Taran - we're just trying to get to a situation where examples can run in CI so that they are automatically up to date with library code.

@donatello You cannot run examples to validate the server or `minio-py` because we need to much more logic for that e.g. to test `get_bucket_versioning()`, you need an existing bucket and `set_bucket_versioning()` called in prior. We can only check these examples are valid at par with current `minio-py` APIs. This is done by `pyflakes` like tools like compilers do rather complicating examples. We should add more tests/checks in functional tests which is really helpful than these changes in examples.

**Pull request closed without merging**
