### PR TITLE
Refactor XML handling of _list_objects()

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by Praveenrajmani** [comment]
Can you fix the conflicts @balamurugana

**Review by kannappanr — APPROVED** [review]
LGTM

**Review by Praveenrajmani — APPROVED** [review]

**Comment by Praveenrajmani** [comment]
Can you fix the conflicts? @balamurugana

**Review by Praveenrajmani — APPROVED** [review]

**Review by kannappanr — APPROVED** [review]

**Pull request merged**
