### PR TITLE
:memo: Add types to the minio client constructor

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**
Fixes part of #1212

### CODE REVIEW

**Comment by balamurugana** [comment]
I am making this PR as draft to fix remaining.

**Comment by gabrieldemarmiesse** [comment]
Would you prefer one big pull request or multiple smaller pull requests? I'm used to split them, but I can do all the changes in the same pull request if you prefer

**Comment by harshavardhana** [comment]
> Would you prefer one big pull request or multiple smaller pull requests? I'm used to split them, but I can do all the changes in the same pull request if you prefer

A single PR is fine @gabrieldemarmiesse

**Comment by balamurugana** [comment]
Stale PR. Resubmit if required.

**Pull request closed without merging**
