### PR TITLE
refactor VersioningConfig with embedded XML handling

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]
LGTM

**Comment by vadmeste** [comment]
```
Traceback (most recent call last):
  File "get_bucket_versioning.py", line 31, in <module>
    config = client.get_bucket_versioning("vadmeste-testver")
  File "/home/anis/work/python/minio-py/minio/api.py", line 911, in get_bucket_versioning
    return unmarshal(VersioningConfig, response.data.encode())
AttributeError: 'bytes' object has no attribute 'encode'
```

@balamurugana getting bucket versioning does not work ^

**Comment by balamurugana** [comment]
@vadmeste 
> @balamurugana getting bucket versioning does not work ^

Fixed the typo.

**Comment by vadmeste** [comment]
@balamurugana LGTM, but there is a conflict now.

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
