### PR TITLE
any specific url expiry positive time, default time is 7 days

### PR DESCRIPTION
**Pull request by alienr**
removing fixed url expiry time, making it any positive time.

### CODE REVIEW

**Comment by vadmeste** [comment]
Thanks for this PR @alienr,

Can you elaborate why this patch is needed ?

**Comment by alienr** [comment]
thanks for your reply @vadmeste ,

I'm storing presigned urls into database, and If after 7 days it gets expired then I have to create the same again. so I was thinking about a positive expiry time only. there should be expiry of url as feature but it should not be a restriction.

**Comment by vadmeste** [comment]
@alienr do you mean that you are using an S3 server that is not respecting 7 days maximum expiry of presigned urls ? I am not aware of any.

**Comment by alienr** [comment]
@vadmeste Okay If I want to set expiry time 15 days, the current minio-py will not allow me.

**Comment by alienr** [comment]
So I want flexible expiry time, not only 7 days.

**Comment by harshavardhana** [comment]
S3 API mandates 7 days expiry. Minio server doesn't support 15 days URL expiries.  The current code is in accordance with S3 API requirements we don't need this PR.

**Comment by alienr** [comment]
Hi, @harshavardhana 
the problem I'm facing is when I'm passing expiry time more than 7 days, minio-py throwing error (Expires param valid values are between 1 sec to 604800). so I'm not able to set greater expiry time than 7 days. AWS S3 allows any positive value as expiry time. 
Please explain why expiry time is restricted to 7 days only.

**Comment by harshavardhana** [comment]
> the problem I'm facing is when I'm passing expiry time more than 7 days, minio-py throwing error (Expires param valid values are between 1 sec to 604800). so I'm not able to set greater expiry time than 7 days. AWS S3 allows any positive value as expiry time.
> Please explain why expiry time is restricted to 7 days only.

This is only true for AWS Signature V2, minio-py only implements Signature V4. https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

`X-Amz-Expires` - Provides the time period, in seconds, for which the generated presigned URL is valid. For example, 86400 (24 hours). This value is an integer. The minimum value you can set is 1, and the maximum is 604800 (seven days). A presigned URL can be valid for a maximum of seven days because the signing key you use in signature calculation is valid for up to seven days.

**Comment by kannappanr** [comment]
As explained by @harshavardhana , S3 signature V4 supports a maximum of 7 days for `X-Amz-Expires`. So, closing this PR as it violates S3 compatibility.

**Comment by alienr** [comment]
thanks

**Pull request closed without merging**
