### PR TITLE
Fixes needed because of the move from request to urllib3

### PR DESCRIPTION
**Pull request by krishnasrinivas**

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
let me check.

**Comment by krishnasrinivas** [comment]
Looks like a bug on requests (https://github.com/kennethreitz/requests/issues/1561) and urllib3 (https://github.com/shazow/urllib3/issues/236)

**Comment by harshavardhana** [comment]
Interesting, did not know when they changed this behavior.

**Comment by harshavardhana** [comment]
Perhaps its requests v/s urllib3

**Comment by krishnasrinivas** [comment]
@harshavardhana requests also has the same behavior. Maybe we used different version of request during development? check here github.com/kennethreitz/requests/issues/1561

**Comment by harshavardhana** [comment]
> @harshavardhana requests also has the same behavior. Maybe we used different version of request during development? check here github.com/kennethreitz/requests/issues/1561

yeah strange indeed, i wonder if there were working properly at all :(

**Pull request merged**
