### PR TITLE
Refactor XML handling of select_object_content() API

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Comment by BigUstad** [comment]
The object used in the call exists in s3. It is also copied to the locally running minio server.
For the ame object in s3, minio; minio downloads the file correctly but s3 doesn't..
And examples/select_object_content.py

`client = Minio('s3.amazonaws.com',
               access_key='<ACCESS_KEY_VALUE>',
               secret_key='<SECRET_KEY_VALUE>')`

For locally running minio server.
`client = Minio('192.168.1.2:9000',
            access_key='<ACCESS_KEY_VALUE>',
            secret_key='<SECRET_KEY_VALUE>',
            secure=False)`


Trace (requests only)
GET /pribkt3?location= HTTP/1.1
Host: 192.168.1.2:9000
User-Agent: MinIO (Darwin; x86_64) minio-py/7.0.0
X-Amz-Content-Sha256: <SHA256 value>
X-Amz-Date: 20201015T212037Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201015/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

GET /?location= HTTP/1.1
Host: amazonaws.com
User-Agent: MinIO (Darwin; x86_64) minio-py/7.0.0
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20201015T212037Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201015/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

which results in this error:

`Traceback (most recent call last):
  File "examples/select_object_content.py", line 57, in <module>
    data = client.select_object_content('pribkt3', 'samplecsvdata/archive/TotalPopulationByGender.csv.gz', request)
<Trace...>
minio.error.S3Error: S3 operation failed; code: AllAccessDisabled, message: All access to this object has been disabled, resource: None, request_id: AE024B3CFA45B583, host_id:<value>`

**Review by BigUstad — COMMENTED** [review]
Please look exceptions of client with s3 server.

**Comment by balamurugana** [comment]
> Please look exceptions of client with s3 server.

Please use the fix https://github.com/minio/minio-py/pull/1004

**Review by ebozduman — APPROVED** [review]
LGTM

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
