### PR TITLE
multipart: Disable resuming incomplete uploads

### LINKED ISSUE #541: Disable resuming uploads
Do not fetch old uploads id and resume them. Instead create a new upload id each time we upload a new multipart.

### PR DESCRIPTION
**Pull request by vadmeste**
Fixes #541

### CODE REVIEW

**Comment by vadmeste** [comment]
Now, fput_object just calls put_object. I don't see why not, also tests are passing.

 @harshavardhana, can you comment on this ? I will made more tests if you don't contest this change.

**Comment by vadmeste** [comment]
This change is not WIP anymore. fput_object and put_object have common code path now.

fput_object() a f1gb file consumes RSS 32MB in contrary to RSS 16MB before this PR.

I think we can accept this compromise to avoid code duplication.

**Comment by donatello** [comment]
> fput_object() a f1gb file consumes RSS 32MB in contrary to RSS 16MB before this PR.
> I think we can accept this compromise to avoid code duplication.

I am ok with the compromise, but I would like to understand why the memory consumption went up. Could you explain @vadmeste ?

**Comment by vadmeste** [comment]
> I am ok with the compromise, but I would like to understand why the memory consumption went up. Could you explain @vadmeste ?

@donatello, put_object considers that the input reader is not seekable, so it allocates memory to save data to calculate hash and then send data to the server via PUT part request.

fput_object plays with file.seek(), it reads the file twice (again for hash and for PUT part) without having the obligation to save any data in the memory (syscalls and the kernel would take care of that).

Now, you would say that we save the whole data twice  in the memory.. that's true.. but it looks like the garbage collector frees data that we don't need anymore, that's what I concluded when I followed memory consumption during upload of 1Gb file.

**Pull request merged**
