### PR TITLE
Refactor XML handling of {set,get,delete}_bucket_notification APIs

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Review by kannappanr — DISMISSED** [review]

**Review by kannappanr — DISMISSED** [review]
LGTM

**Review by kannappanr — DISMISSED** [review]

**Review by ebozduman — CHANGES_REQUESTED** [review]
@balamurugana Bala,

I ran a `set_bucket_notification` test on my setup, and I see a `TypeError`:

`TypeError: SubElement() argument 1 must be xml.etree.ElementTree.Element, not QueueConfig`

My MinIO server is the usual single/regular/stand-alone minio server
`minio server <data-location>`

I created a Redis notification config setting and then rebooted minio server,

Here is the `mc` command, I used to set the notifyconfiguration parameters
to generate arn`:
```
$ mc admin config set myminio/ notify_redis:1 address="127.0.0.1:6379" format="namespace" key="bucketevents" password="yoursecret" queue_dir="" queue_limit="0"
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio/`.
```

Here is the test script:
```
from minio import Minio
from minio.notificationconfig import (NotificationConfig, PrefixFilterRule,
                                      QueueConfig)

client = Minio(
    "localhost:9000",
    access_key="minio",
    secret_key="minio123",
    secure=False,
)

config = NotificationConfig(
    queue_config_list=[
        QueueConfig(
            "arn:minio:sqs:us-east-1:1:redis",
            ['s3:ObjectCreated:*'],
            config_id="1",
            prefix_filter_rule=PrefixFilterRule("abc"),
        ),
    ],
)

client.set_bucket_notification("bucket", config)
```

Running the above script throws the following error:

```
$ python3.8 run_set_bucket_notification.py 
Traceback (most recent call last):
  File "run_set_bucket_notification.py", line 47, in <module>
    client.set_bucket_notification("bucket", config)
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/api.py", line 753, in set_bucket_notification
    body = marshal(config)
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/xml.py", line 100, in marshal
    return getbytes(obj.toxml(None))
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/notificationconfig.py", line 313, in toxml
    config.toxml(config)
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/notificationconfig.py", line 219, in toxml
    element = SubElement(element, "QueueConfiguration")
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/xml.py", line 35, in SubElement
    element = ET.SubElement(parent, tag)
TypeError: SubElement() argument 1 must be xml.etree.ElementTree.Element, not QueueConfig
```
Let me know if you would like make some changes and run the test. My setup is up and running.

**Comment by balamurugana** [comment]
@ebozduman fixed and updated this PR

**Comment by ebozduman** [comment]
Great! Testing it again after sync

**Review by ebozduman — CHANGES_REQUESTED** [review]
Now, `get_bucket_notification` api is having another type issue:
```
$ python3.8 run_get_bucket_notification.py 
Traceback (most recent call last):
  File "run_get_bucket_notification.py", line 33, in <module>
    config = client.get_bucket_notification("bucket")
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/api.py", line 728, in get_bucket_notification
    return unmarshal(NotificationConfig, response.data.decode())
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/xml.py", line 85, in unmarshal
    return cls.fromxml(ET.fromstring(xmlstring))
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/notificationconfig.py", line 298, in fromxml
    queue_config_list.append(QueueConfig.fromxml(tag))
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/notificationconfig.py", line 208, in fromxml
    suffix_filter_rule) = cls.parsexml(element)
  File "/home/ersan/work/src/github.com/minio/minio-py/minio/notificationconfig.py", line 125, in parsexml
    if filter_rule.name() == "prefix":
TypeError: 'str' object is not callable
```

**Comment by balamurugana** [comment]
@ebozduman 
> Now, `get_bucket_notification` api is having another type issue:

Fixed and updated the PR

**Comment by ebozduman** [comment]
By the way, here is the script I use to get bucket notification configuration, if any:
```
from minio import Minio

client = Minio("localhost:9000",
    access_key="minio",
    secret_key="minio123",
    secure=False,
)

config = client.get_bucket_notification("bucket")
print(vars(config))
```

**Comment by balamurugana** [comment]
> By the way, here is the script I use to get bucket notification configuration, if any:

@ebozduman There was a problem in naming unit test file caused the tests wasn't kicked in. I fixed that as well.

**Review by ebozduman — APPROVED** [review]
Tests are successfully completed.
As notification is triggered (creation of objects under bucket, `"bucket"`, and with the name prefix `"abc"`), I see data coming to redis client and redis server.
LGTM

**Pull request merged**
