### PR TITLE
Refactor XML handling of _list_parts() API

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Review by vadmeste — COMMENTED** [review]
LGTM, but _list_parts does not seem to be called anymore.

**Comment by balamurugana** [comment]
@vadmeste 
> LGTM, but _list_parts does not seem to be called anymore.

Yes. As we have removed list_multipart_uploads() API (because of no way to create incomplete uploads in `minio-py`), It is available for advanced usage.

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by BigUstad — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Pull request merged**
