### PR TITLE
api:put_object not saving user metadata without x-amz-meta- prefix 

### LINKED ISSUE #655: put_object doesn't save metadata. save only 'x-amz-meta-KEY' keys
**Description:**
When I try to save dict to metadata with put_object, 
it saves only keys which starts with 'x-amz-meta'
all other key are ignored, nested dicts are rising errors

**Versions:** 
3.0.5 and 4.0.0

**sample code to reproduce:**
```python
import minio
import io
client = minio.Minio('localhost:9000')
data_str="somestr"
oname='pp/gg.txt'
data = io.BytesIO(jpeg_str.encode())
client.put_object('uploads', oname, data, len(data_str), metadata= {
    'x-amz-meta-testing': 'values',
    'x-amz-meta-setting': 'zombies',
    'amz-meta-setting': 'zombiesddd',
    'hhh':34,
    'u_u': 'dd',
    'y-fu-bar': 'zoo'
})
stat = client.stat_object('uploads', oname)
print(stat.metadata)
```
**Actual output:**
> {'X-Amz-Meta-Setting': 'zombies', 'X-Amz-Meta-Testing': 'values'}

**Expected output:**
same as original metadata dict

Is it by design?

### PR DESCRIPTION
**Pull request by poornas**
Fixes #655 

 Append x-amz-meta- prefix for user defined meta data if not already prefixed.

### CODE REVIEW

**Comment by poornas** [comment]
@harshavardhana  and @ebozduman , this needs your review.

**Comment by harshavardhana** [comment]
tests are not running @poornas

**Comment by poornas** [comment]
@harshavardhana , looks like play server is not accepting new connxns, hence the travis fail

**Comment by harshavardhana** [comment]
> @harshavardhana , looks like play server is not accepting new connxns, hence the travis fail

play is restarted...

**Pull request merged**
