### PR TITLE
Refactor XML handling of _complete_multipart_upload() API

### PR DESCRIPTION
**Pull request by balamurugana**

### CODE REVIEW

**Comment by vadmeste** [comment]
@balamurugana can you resolve conflicts of this PR ? some testing fails, probably will be resolved after rebasing it.

**Comment by vadmeste** [comment]
@balamurugana something is wrong with this PR. I am not able to upload an object with 10mb, with this weird error:

```
S3 operation failed; code: AllAccessDisabled, message: All access to this object has been disabled, resource: None, request_id: 9E51F9F4EEB28241, host_id: T3PvcbI1hUehlq6rjchEmiWxL9kOeaEBaO6x+bRWioXO8oDkWNYRQ3NWSaRLCEFo0F79ncdhltI=
```

Though it works fine with master.

Could you check ?

**Comment by balamurugana** [comment]
> @balamurugana something is wrong with this PR. I am not able to upload an object with 10mb, with this weird error:
> 
> ```
> S3 operation failed; code: AllAccessDisabled, message: All access to this object has been disabled, resource: None, request_id: 9E51F9F4EEB28241, host_id: T3PvcbI1hUehlq6rjchEmiWxL9kOeaEBaO6x+bRWioXO8oDkWNYRQ3NWSaRLCEFo0F79ncdhltI=
> ```
> 
> Though it works fine with master.
> 
> Could you check ?

This failure happens when no region passed for the endpoint in the master. https://github.com/minio/minio-py/pull/1004 fixes the issue.

**Review by kannappanr — DISMISSED** [review]
LGTM

**Review by vadmeste — APPROVED** [review]
LGTM & tested

**Review by kannappanr — APPROVED** [review]
LGTM

**Pull request merged**
